modLoader="javafml" 
loaderVersion="[47,)"
license="MIT"
[[mods]] 
modId="goldenberry"
version="${file.jarVersion}" 
displayName="Golden Berries"
logoFile="icon.png"
authors="AzureDoom"
description='''
Adds a Golden Berry that is similar to the Golden Carrot.
'''
[[dependencies.goldenberry]]
    modId="forge" 
    mandatory=true 
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goldenberry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
